import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';
import type { 
  CommercialDocument, 
  CommercialDocumentPhase, 
  CommercialDocumentItem,
  DocumentType,
  ProjectType,
  DocumentStatus,
  FeeMode
} from '@/lib/commercialTypes';

export interface CreateDocumentInput {
  document_type: DocumentType;
  title: string;
  description?: string;
  client_company_id?: string;
  client_contact_id?: string;
  project_type: ProjectType;
  project_address?: string;
  project_city?: string;
  project_surface?: number;
  project_budget?: number;
  fee_mode?: FeeMode;
  fee_percentage?: number;
  hourly_rate?: number;
  validity_days?: number;
  payment_terms?: string;
  special_conditions?: string;
  general_conditions?: string;
}

export interface UpdateDocumentInput extends Partial<CreateDocumentInput> {
  id: string;
  status?: DocumentStatus;
  total_amount?: number;
  valid_until?: string;
  sent_at?: string;
  accepted_at?: string;
  signed_at?: string;
  project_id?: string;
}

export interface CreatePhaseInput {
  document_id: string;
  phase_code: string;
  phase_name: string;
  phase_description?: string;
  percentage_fee?: number;
  amount?: number;
  is_included?: boolean;
  deliverables?: string[];
  start_date?: string;
  end_date?: string;
  sort_order?: number;
}

export interface UpdatePhaseInput extends Partial<CreatePhaseInput> {
  id: string;
}

export interface CreateItemInput {
  document_id: string;
  phase_id?: string;
  item_type: 'mission' | 'option' | 'expense' | 'discount';
  description: string;
  quantity?: number;
  unit?: string;
  unit_price?: number;
  amount?: number;
  is_optional?: boolean;
  sort_order?: number;
}

export const useCommercialDocuments = () => {
  const { activeWorkspace } = useAuth();
  const queryClient = useQueryClient();

  const documentsQuery = useQuery({
    queryKey: ['commercial-documents', activeWorkspace?.id],
    queryFn: async () => {
      if (!activeWorkspace?.id) return [];

      const { data, error } = await supabase
        .from('commercial_documents')
        .select(`
          *,
          client_company:crm_companies(id, name, logo_url),
          client_contact:contacts(id, name, email),
          project:projects(id, name)
        `)
        .eq('workspace_id', activeWorkspace.id)
        .order('created_at', { ascending: false });

      if (error) throw error;
      return data as CommercialDocument[];
    },
    enabled: !!activeWorkspace?.id
  });

  const getDocument = (id: string) => {
    return useQuery({
      queryKey: ['commercial-document', id],
      queryFn: async () => {
        const { data, error } = await supabase
          .from('commercial_documents')
          .select(`
            *,
            client_company:crm_companies(id, name, logo_url),
            client_contact:contacts(id, name, email),
            project:projects(id, name)
          `)
          .eq('id', id)
          .single();

        if (error) throw error;
        return data as CommercialDocument;
      },
      enabled: !!id
    });
  };

  const getDocumentPhases = (documentId: string) => {
    return useQuery({
      queryKey: ['commercial-document-phases', documentId],
      queryFn: async () => {
        const { data, error } = await supabase
          .from('commercial_document_phases')
          .select('*')
          .eq('document_id', documentId)
          .order('sort_order');

        if (error) throw error;
        return data as CommercialDocumentPhase[];
      },
      enabled: !!documentId
    });
  };

  const getDocumentItems = (documentId: string) => {
    return useQuery({
      queryKey: ['commercial-document-items', documentId],
      queryFn: async () => {
        const { data, error } = await supabase
          .from('commercial_document_items')
          .select('*')
          .eq('document_id', documentId)
          .order('sort_order');

        if (error) throw error;
        return data as CommercialDocumentItem[];
      },
      enabled: !!documentId
    });
  };

  const createDocument = useMutation({
    mutationFn: async (input: CreateDocumentInput) => {
      if (!activeWorkspace?.id) throw new Error('No workspace');

      const { data: { user } } = await supabase.auth.getUser();

      const { data, error } = await supabase
        .from('commercial_documents')
        .insert({
          ...input,
          workspace_id: activeWorkspace.id,
          created_by: user?.id,
          document_number: '' // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['commercial-documents'] });
      toast.success('Document créé');
    },
    onError: (error) => {
      toast.error('Erreur lors de la création');
      console.error(error);
    }
  });

  const updateDocument = useMutation({
    mutationFn: async ({ id, ...input }: UpdateDocumentInput) => {
      const { data, error } = await supabase
        .from('commercial_documents')
        .update(input)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['commercial-documents'] });
      queryClient.invalidateQueries({ queryKey: ['commercial-document', data.id] });
      toast.success('Document mis à jour');
    },
    onError: (error) => {
      toast.error('Erreur lors de la mise à jour');
      console.error(error);
    }
  });

  const deleteDocument = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from('commercial_documents')
        .delete()
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['commercial-documents'] });
      toast.success('Document supprimé');
    },
    onError: (error) => {
      toast.error('Erreur lors de la suppression');
      console.error(error);
    }
  });

  // Phases mutations
  const createPhase = useMutation({
    mutationFn: async (input: CreatePhaseInput) => {
      const { data, error } = await supabase
        .from('commercial_document_phases')
        .insert({
          ...input,
          deliverables: input.deliverables || []
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['commercial-document-phases', data.document_id] });
    }
  });

  const updatePhase = useMutation({
    mutationFn: async ({ id, ...input }: UpdatePhaseInput) => {
      const { data, error } = await supabase
        .from('commercial_document_phases')
        .update(input)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['commercial-document-phases', data.document_id] });
    }
  });

  const deletePhase = useMutation({
    mutationFn: async ({ id, documentId }: { id: string; documentId: string }) => {
      const { error } = await supabase
        .from('commercial_document_phases')
        .delete()
        .eq('id', id);

      if (error) throw error;
      return { documentId };
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['commercial-document-phases', data.documentId] });
    }
  });

  const updatePhasesOrder = useMutation({
    mutationFn: async ({ phases, documentId }: { phases: { id: string; sort_order: number }[]; documentId: string }) => {
      const updates = phases.map(p => 
        supabase
          .from('commercial_document_phases')
          .update({ sort_order: p.sort_order })
          .eq('id', p.id)
      );

      await Promise.all(updates);
      return { documentId };
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['commercial-document-phases', data.documentId] });
    }
  });

  // Items mutations
  const createItem = useMutation({
    mutationFn: async (input: CreateItemInput) => {
      const { data, error } = await supabase
        .from('commercial_document_items')
        .insert(input)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['commercial-document-items', data.document_id] });
    }
  });

  const deleteItem = useMutation({
    mutationFn: async ({ id, documentId }: { id: string; documentId: string }) => {
      const { error } = await supabase
        .from('commercial_document_items')
        .delete()
        .eq('id', id);

      if (error) throw error;
      return { documentId };
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['commercial-document-items', data.documentId] });
    }
  });

  return {
    documents: documentsQuery.data || [],
    isLoading: documentsQuery.isLoading,
    getDocument,
    getDocumentPhases,
    getDocumentItems,
    createDocument,
    updateDocument,
    deleteDocument,
    createPhase,
    updatePhase,
    deletePhase,
    updatePhasesOrder,
    createItem,
    deleteItem
  };
};
