// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fblmuttvuacqahvygudd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZibG11dHR2dWFjcWFodnlndWRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyMDc4OTksImV4cCI6MjA4NDc4Mzg5OX0.i8Oo94YekOQrGFwcGyjFE6ZKyXprkuCj_P5i6zt5jwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});